version: "3"

services:
    server:
        container_name: nginxapp
        image: nginx
        port:
            - "5000:80"
    db:
        container_name: mypostgres
        image: postgres:10
        environment:
            - 
        volumes:
            - odoo-db-postgres:/var/lib/postgresql/data/pgdata
    odoo:
        container_name: odoo13
        image: odoo:13.0
        depends_on: 
            - db
        ports:
            - "8069:8069"
        volumes:
            - odoo-data:/var/lib/data
            - ./config:/etc/odoo
            - ./addons:/mnt/extra-addons
volume:
    odoo-data
    odoo-db-postgres
