CREATE USER odoo131 WITH PASSWORD 'odoo';

CREATE DATABASE odoo131;
GRANT ALL PRIVILEGES ON DATABASE odoo131 TO odoo131;

CREATE USER odoo132 WITH PASSWORD 'odoo';

CREATE DATABASE odoo132;
GRANT ALL PRIVILEGES ON DATABASE odoo132 TO odoo132;

CREATE USER odoo133 WITH PASSWORD 'odoo';

CREATE DATABASE odoo133;
GRANT ALL PRIVILEGES ON DATABASE odoo133 TO odoo133;